usr/include/+(ignition|gz)/sensors*/gz/sensors/air_pressure/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/AirPressure*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/air_pressure/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/AirPressure*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-air_pressure/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-air_pressure.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-air_pressure.pc
