usr/include/+(ignition|gz)/sensors*/gz/sensors/rendering/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/Rendering*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/rendering/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/Rendering*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-rendering/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-rendering.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-rendering.pc
