usr/include/+(ignition|gz)/sensors*/gz/sensors/magnetometer/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/Magnetometer*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/magnetometer/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/Magnetometer*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-magnetometer/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-magnetometer.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-magnetometer.pc
