usr/include/+(ignition|gz)/sensors*/gz/sensors/navsat/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/NavSat*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/navsat/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/NavSat*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-navsat/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-navsat.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-navsat.pc
