usr/include/+(ignition|gz)/sensors*/gz/sensors/depth_camera/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/DepthCamera*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/depth_camera/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/DepthCamera*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-depth_camera/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-depth_camera.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-depth_camera.pc
