usr/include/+(ignition|gz)/sensors*/gz/sensors/segmentation_camera/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/SegmentationCamera*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/segmentation_camera/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/SegmentationCamera*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-segmentation_camera/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-segmentation_camera.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-segmentation_camera.pc
