usr/include/+(ignition|gz)/sensors*/gz/sensors/thermal_camera/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/ThermalCamera*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/thermal_camera/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/ThermalCamera*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-thermal_camera/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-thermal_camera.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-thermal_camera.pc
