usr/include/+(ignition|gz)/sensors*/gz/sensors/lidar/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/Lidar*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/lidar/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/Lidar*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-lidar/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-lidar.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-lidar.pc
