usr/include/ignition/sensors[0-99]/gz/sensors.hh
usr/include/ignition/sensors[0-99]/gz/sensors/*.hh
usr/include/ignition/sensors[0-99]/gz/sensors/detail/*.hh
usr/include/ignition/sensors[0-99]/ignition/sensors.hh
usr/include/ignition/sensors[0-99]/ignition/sensors/*.hh
usr/lib/*/libignition-sensors[0-99].so
usr/lib/*/pkgconfig/ignition-sensors[0-99].pc
usr/lib/*/cmake/ignition-sensors[0-99]/ignition-sensors*
