usr/include/+(ignition|gz)/sensors*/gz/sensors/force_torque/*
usr/include/+(ignition|gz)/sensors*/gz/sensors/ForceTorque*.hh
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/force_torque/*
usr/include/+(ignition|gz)/sensors*/+(ignition|gz)/sensors/ForceTorque*.hh
usr/lib/*/cmake/+(ignition|gz)-sensors[0-99]-force_torque/*
usr/lib/*/lib+(ignition|gz)-sensors[0-99]-force_torque.so
usr/lib/*/pkgconfig/+(ignition|gz)-sensors[0-99]-force_torque.pc
